# Generated by Django 4.2.23 on 2025-08-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
