# Generated by Django 4.2.23 on 2025-08-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_notification_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='edited',
        ),
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
